// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu2dgDCfPdPpaHpdGqwkeZ-s8xLk7MVCk',
    appId: '1:626090928458:web:ff7fd2c47c0010c174b9b3',
    messagingSenderId: '626090928458',
    projectId: 'fitrushapp',
    authDomain: 'fitrushapp.firebaseapp.com',
    storageBucket: 'fitrushapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2HAsDmLbdiVSkLm9LrCioT75_nC9mEMk',
    appId: '1:626090928458:android:61c05408b0b5b3de74b9b3',
    messagingSenderId: '626090928458',
    projectId: 'fitrushapp',
    storageBucket: 'fitrushapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuqqNsaKW-J2tDwkyvJ9P9LQDfJowVMK0',
    appId: '1:626090928458:ios:b085e567c5eedbf774b9b3',
    messagingSenderId: '626090928458',
    projectId: 'fitrushapp',
    storageBucket: 'fitrushapp.firebasestorage.app',
    iosBundleId: 'com.example.fitRushApp',
  );
}
